#include "midi/midi_mapping.h"

#include <errno.h>
#include <stdio.h>
#include <string.h>

// writes controller assignments and ranges, never live synth values or pickup state
// returns failure with a readable error when validation or file writing fails
int midi_mapping_save(const midi_mapping *mapping, const char *path, char *error, size_t error_size)
{
    FILE *file;
    if (mapping == NULL || path == NULL || mapping->binding_count > MIDI_MAPPING_MAX_BINDINGS) {
        if (error != NULL && error_size > 0) snprintf(error, error_size, "invalid mapping");
        return 0;
    }
    // check direct bindings before opening with "w", which would truncate the file
    for (size_t i = 0; i < mapping->binding_count; ++i) {
        if (!midi_mapping_validate_binding(&mapping->bindings[i], error, error_size)) return 0;
    }
    file = fopen(path, "w");

    if (file == 0) {
        if (error != NULL && error_size > 0) snprintf(error, error_size, "%s", strerror(errno));
        return 0;
    }

    fprintf(file, "# midi controller mapping generated by midi_monitor learn\n");
    fprintf(file, "name=%s\n\n", mapping->name);
    fprintf(file, "# format: parameter=cc:channel:control:scale:min:max\n");

    for (size_t i = 0; i < mapping->binding_count; ++i) {
        const midi_mapping_binding *binding = &mapping->bindings[i];

        if (binding->source_type == MIDI_MAPPING_SOURCE_CC) {
            midi_mapping_parameter_info info;
            if (!midi_mapping_parameter_info_for(binding->parameter, binding->target_kind, &info)) {
                fclose(file);
                if (error != NULL && error_size > 0) snprintf(error, error_size, "invalid control target");
                return 0;
            }
            // nine significant digits preserve a 32-bit float's value across a
            // text round trip, including custom ranges with many decimal places
            fprintf(
                file,
                "%s=cc:%d:%d:%s:%.9g:%.9g\n",
                info.name,
                binding->channel,
                binding->control,
                midi_mapping_scale_name(binding->scale),
                binding->min_value,
                binding->max_value);
        }
    }

    fprintf(file, "\n# format: effect_selector_N/effect_N_macro_M=cc:channel:control\n");
    for (size_t bank_index = 0; bank_index < MIDI_MAPPING_EFFECT_BANK_COUNT; ++bank_index) {
        const midi_mapping_effect_bank *bank = &mapping->effect_banks[bank_index];

        if (bank->selector.enabled &&
            bank->selector.source_type == MIDI_MAPPING_SOURCE_CC) {
            fprintf(
                file,
                "%s=cc:%d:%d\n",
                midi_mapping_effect_selector_name(bank_index),
                bank->selector.channel,
                bank->selector.control);
        }

        for (size_t i = 0; i < MIDI_MAPPING_EFFECT_MACRO_COUNT; ++i) {
            const midi_mapping_control_binding *binding = &bank->macros[i];

            if (binding->enabled && binding->source_type == MIDI_MAPPING_SOURCE_CC) {
                fprintf(
                    file,
                    "%s=cc:%d:%d\n",
                    midi_mapping_effect_macro_name(bank_index, i),
                    binding->channel,
                    binding->control);
            }
        }
    }

    fprintf(file, "\n# format: chord_pad=cc:channel:control\n");
    for (size_t i = 0; i < MIDI_CHORD_MODE_PAD_COUNT; ++i) {
        const midi_mapping_chord_binding *binding = &mapping->chord_bindings[i];

        if (binding->enabled && binding->source_type == MIDI_MAPPING_SOURCE_CC) {
            fprintf(
                file,
                "%s=cc:%d:%d\n",
                midi_mapping_chord_pad_name(binding->pad),
                binding->channel,
                binding->control);
        }
    }

    {
        // buffered writes can fail when closing, so check both the stream and close
        const int failed = ferror(file);
        const int close_failed = fclose(file) != 0;
        if (failed || close_failed) {
            if (error != NULL && error_size > 0) snprintf(error, error_size, "could not finish writing config");
            return 0;
        }
    }
    return 1;
}
